### ISSUE TITLE
Sort by license

### ISSUE THREAD

**Issue by hellocatfood** [ilesinge/shabda#1]
Can an option be added to filter the downloaded/collected samples by license type? This will be especially useful for users of the cli version who want to then use the samples in a commercial project and not be restricted by license.

**Comment by ilesinge** [comment]
This is definitely something useful, and it could be done since the license type is available in the API.
Thanks for the idea ! I'll look into it.

**Comment by ilesinge** [comment]
This is now available on the web version, only some small work remains to revamp the CLI

**Comment by hellocatfood** [comment]
Great! Do you know how the cli version will work?

**Comment by ilesinge** [comment]
I expect it to be something like:

shabda_cli.py sample1:3,sample2 --licences=cc0

Would that work for you?

Ideally in the future with a simpler installation path.

**Comment by hellocatfood** [comment]
> shabda_cli.py sample1:3,sample2 --licences=cc0

I think something like that would work. Was just wondering how it would handle lincenses that have multiple clauses e.g. cc-by-nc

**Comment by ilesinge** [comment]
It would be:
`shabda_cli.py sample1:3,sample2 --licenses=by-nc`
Multiple values (all accepted licenses) can be defined as such:
`shabda_cli.py sample1:3,sample2 --licenses=by-nc --licenses=by`

Note that I just finished implemented it, I just need to update the README.
It is available on the branch licenses_cli: https://github.com/ilesinge/shabda/tree/licenses_cli

**Comment by ilesinge** [comment]
Implementation now available on the master branch (fixed with https://github.com/ilesinge/shabda/pull/5 )
