### ISSUE TITLE
Append search term to file name

### ISSUE THREAD

**Issue by hellocatfood** [ilesinge/shabda#2]
Would it be possible to append the search term onto each of the downloaded samples (or have an option to do so). 

For example, running `python3 shabda_cli.py cats --num 10
 1517  python3 shabda_cli.py cats --num 10` would create the folder `cats` and each file in the folder would be `1_cats.wav`, `2_cats.wav`, `3_cats.wav` etc.

The use case for this is that I am currently using Shabda to put random samples on an MPC Live. It stores all of the used samples in the same directory, so if two files have the same name they get overwritten.

**Comment by ilesinge** [comment]
That's a totally valid use case :)
I'm gonna tackle this one after #1 .
By the way it's possible that I slightly change the cli arguments.

**Comment by ilesinge** [comment]
Your use case should now be covered in the latest version :)
Please tell me if it fits your needs!
